array_width = 150
max_width = 200
comment_width = 150

edition = "2021"

fn_single_line = true

reorder_imports = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"

match_arm_leading_pipes = "preserve"

